package bav.petus.android.ui.common

import bav.petus.android.R
import bav.petus.core.resources.ImageId

fun ImageId.toResId(): Int {
    return when (this) {
        ImageId.BuryCat -> R.drawable.bury_cat
        ImageId.BuryDog -> R.drawable.bury_dog
        ImageId.BuryFrog -> R.drawable.bury_frog
        ImageId.CleanUpCat -> R.drawable.clean_up_cat
        ImageId.CleanUpDog -> R.drawable.clean_up_dog
        ImageId.CleanUpFrog -> R.drawable.clean_up_frog
        ImageId.FeedCat -> R.drawable.feed_cat
        ImageId.FeedDog -> R.drawable.feed_dog
        ImageId.FeedFrog -> R.drawable.feed_frog
        ImageId.HealCat -> R.drawable.heal_cat
        ImageId.HealDog -> R.drawable.heal_dog
        ImageId.HealFrog -> R.drawable.heal_frog
        ImageId.PlayCat -> R.drawable.play_cat
        ImageId.PlayDog -> R.drawable.play_dog
        ImageId.PlayFrog -> R.drawable.play_frog
        ImageId.ResurrectCat -> R.drawable.resurrect_cat
        ImageId.ResurrectDog -> R.drawable.resurrect_dog
        ImageId.ResurrectFrog -> R.drawable.resurrect_frog
        ImageId.SpeakCat -> R.drawable.speak_cat
        ImageId.SpeakDog -> R.drawable.speak_dog
        ImageId.SpeakFrog -> R.drawable.speak_frog
        ImageId.WakeUpCat -> R.drawable.wake_up_cat
        ImageId.WakeUpDog -> R.drawable.wake_up_dog
        ImageId.WakeUpFrog -> R.drawable.wake_up_frog
        ImageId.CatAdultActive -> R.drawable.catus_adult_active
        ImageId.CatAdultDead -> R.drawable.catus_adult_dead
        ImageId.CatAdultHungry -> R.drawable.catus_adult_hungry
        ImageId.CatAdultIll -> R.drawable.catus_adult_ill
        ImageId.CatAdultPoop -> R.drawable.catus_adult_poop
        ImageId.CatAdultSleep -> R.drawable.catus_adult_sleep
        ImageId.CatAdultZombie -> R.drawable.catus_adult_zombie
        ImageId.CatEgg -> R.drawable.catus_egg
        ImageId.CatGrave -> R.drawable.catus_grave
        ImageId.CatNewbornActive -> R.drawable.catus_newborn_active
        ImageId.CatNewbornDead -> R.drawable.catus_newborn_dead
        ImageId.CatNewbornHungry -> R.drawable.catus_newborn_hungry
        ImageId.CatNewbornIll -> R.drawable.catus_newborn_ill
        ImageId.CatNewbornPoop -> R.drawable.catus_newborn_poop
        ImageId.CatNewbornSleep -> R.drawable.catus_newborn_sleep
        ImageId.CatNewbornZombie -> R.drawable.catus_newborn_zombie
        ImageId.CatOldActive -> R.drawable.catus_old_active
        ImageId.CatOldDead -> R.drawable.catus_old_dead
        ImageId.CatOldHungry -> R.drawable.catus_old_hungry
        ImageId.CatOldIll -> R.drawable.catus_old_ill
        ImageId.CatOldPoop -> R.drawable.catus_old_poop
        ImageId.CatOldSleep -> R.drawable.catus_old_sleep
        ImageId.CatOldZombie -> R.drawable.catus_old_zombie
        ImageId.DogAdultActive -> R.drawable.dogus_adult_active
        ImageId.DogAdultDead -> R.drawable.dogus_dead
        ImageId.DogAdultHungry -> R.drawable.dogus_adult_hungry
        ImageId.DogAdultIll -> R.drawable.dogus_adult_ill
        ImageId.DogAdultPoop -> R.drawable.dogus_adult_poop
        ImageId.DogAdultSleep -> R.drawable.dogus_adult_sleep
        ImageId.DogAdultZombie -> R.drawable.dogus_adult_zombie
        ImageId.DogEgg -> R.drawable.dogus_egg
        ImageId.DogGrave -> R.drawable.dogus_grave
        ImageId.DogNewbornActive -> R.drawable.dogus_newborn_active
        ImageId.DogNewbornDead -> R.drawable.dogus_dead
        ImageId.DogNewbornHungry -> R.drawable.dogus_newborn_hungry
        ImageId.DogNewbornIll -> R.drawable.dogus_newborn_ill
        ImageId.DogNewbornPoop -> R.drawable.dogus_newborn_poop
        ImageId.DogNewbornSleep -> R.drawable.dogus_newborn_sleep
        ImageId.DogNewbornZombie -> R.drawable.dogus_newborn_zombie
        ImageId.DogOldActive -> R.drawable.dogus_old_active
        ImageId.DogOldDead -> R.drawable.dogus_dead
        ImageId.DogOldHungry -> R.drawable.dogus_old_hungry
        ImageId.DogOldIll -> R.drawable.dogus_old_ill
        ImageId.DogOldPoop -> R.drawable.dogus_old_poop
        ImageId.DogOldSleep -> R.drawable.dogus_old_sleep
        ImageId.DogOldZombie -> R.drawable.dogus_old_zombie
        ImageId.FrogAdultActive -> R.drawable.frogus_adult_active
        ImageId.FrogAdultDead -> R.drawable.frogus_dead
        ImageId.FrogAdultHungry -> R.drawable.frogus_adult_hungry
        ImageId.FrogAdultIll -> R.drawable.frogus_adult_ill
        ImageId.FrogAdultPoop -> R.drawable.frogus_adult_poop
        ImageId.FrogAdultSleep -> R.drawable.frogus_adult_sleep
        ImageId.FrogAdultZombie -> R.drawable.frogus_adult_zombie
        ImageId.FrogEgg -> R.drawable.frogus_egg
        ImageId.FrogGrave -> R.drawable.frogus_grave
        ImageId.FrogNewbornActive -> R.drawable.frogus_newborn_active
        ImageId.FrogNewbornDead -> R.drawable.frogus_dead
        ImageId.FrogNewbornHungry -> R.drawable.frogus_newborn_hungry
        ImageId.FrogNewbornIll -> R.drawable.frogus_newborn_ill
        ImageId.FrogNewbornPoop -> R.drawable.frogus_newborn_poop
        ImageId.FrogNewbornSleep -> R.drawable.frogus_newborn_sleep
        ImageId.FrogNewbornZombie -> R.drawable.frogus_newborn_zombie
        ImageId.FrogOldActive -> R.drawable.frogus_old_active
        ImageId.FrogOldDead -> R.drawable.frogus_dead
        ImageId.FrogOldHungry -> R.drawable.frogus_old_hungry
        ImageId.FrogOldIll -> R.drawable.frogus_old_ill
        ImageId.FrogOldPoop -> R.drawable.frogus_old_poop
        ImageId.FrogOldSleep -> R.drawable.frogus_old_sleep
        ImageId.FrogOldZombie -> R.drawable.frogus_old_zombie
        ImageId.BoberAdultActive -> R.drawable.bober_adult_active
        ImageId.BoberAdultDead -> R.drawable.bober_adult_dead
        ImageId.BoberAdultHungry -> R.drawable.bober_adult_hungry
        ImageId.BoberAdultIll -> R.drawable.bober_adult_ill
        ImageId.BoberAdultPoop -> R.drawable.bober_adult_poop
        ImageId.BoberAdultSleep -> R.drawable.bober_adult_sleep
        ImageId.BoberAdultZombie -> R.drawable.bober_adult_zombie
        ImageId.BoberEgg -> R.drawable.bober_egg
        ImageId.BoberGrave -> R.drawable.bober_grave
        ImageId.BoberNewbornActive -> R.drawable.bober_newborn_active
        ImageId.BoberNewbornDead -> R.drawable.bober_newborn_dead
        ImageId.BoberNewbornHungry -> R.drawable.bober_newborn_hungry
        ImageId.BoberNewbornIll -> R.drawable.bober_newborn_ill
        ImageId.BoberNewbornPoop -> R.drawable.bober_newborn_poop
        ImageId.BoberNewbornSleep -> R.drawable.bober_newborn_sleep
        ImageId.BoberNewbornZombie -> R.drawable.bober_newborn_zombie
        ImageId.BoberOldActive -> R.drawable.bober_old_active
        ImageId.BoberOldDead -> R.drawable.bober_old_dead
        ImageId.BoberOldHungry -> R.drawable.bober_old_hungry
        ImageId.BoberOldIll -> R.drawable.bober_old_ill
        ImageId.BoberOldPoop -> R.drawable.bober_old_poop
        ImageId.BoberOldSleep -> R.drawable.bober_old_sleep
        ImageId.BoberOldZombie -> R.drawable.bober_old_zombie
        ImageId.DugOutGrave -> R.drawable.dug_out_grave
        ImageId.UserProfileAvatar -> R.drawable.user_profile_avatar
    }
}
