package bav.petus.android.ui.common

import bav.petus.android.R
import bav.petus.core.inventory.InventoryItemId
import bav.petus.core.resources.ImageId

fun ImageId.toResId(): Int {
    return when (this) {
        ImageId.BuryCat -> R.drawable.bury_cat
        ImageId.BuryDog -> R.drawable.bury_dog
        ImageId.BuryFrog -> R.drawable.bury_frog
        ImageId.CleanUpCat -> R.drawable.clean_up_cat
        ImageId.CleanUpDog -> R.drawable.clean_up_dog
        ImageId.CleanUpFrog -> R.drawable.clean_up_frog
        ImageId.FeedCat -> R.drawable.feed_cat
        ImageId.FeedDog -> R.drawable.feed_dog
        ImageId.FeedFrog -> R.drawable.feed_frog
        ImageId.HealCat -> R.drawable.heal_cat
        ImageId.HealDog -> R.drawable.heal_dog
        ImageId.HealFrog -> R.drawable.heal_frog
        ImageId.PlayCat -> R.drawable.play_cat
        ImageId.PlayDog -> R.drawable.play_dog
        ImageId.PlayFrog -> R.drawable.play_frog
        ImageId.ResurrectCat -> R.drawable.resurrect_cat
        ImageId.ResurrectDog -> R.drawable.resurrect_dog
        ImageId.ResurrectFrog -> R.drawable.resurrect_frog
        ImageId.SpeakCat -> R.drawable.speak_cat
        ImageId.SpeakDog -> R.drawable.speak_dog
        ImageId.SpeakFrog -> R.drawable.speak_frog
        ImageId.WakeUpCat -> R.drawable.wake_up_cat
        ImageId.WakeUpDog -> R.drawable.wake_up_dog
        ImageId.WakeUpFrog -> R.drawable.wake_up_frog
        ImageId.OnboardingHome -> R.drawable.house_on_hill
        ImageId.OnboardingSatiety -> R.drawable.feed_cat_1024
        ImageId.OnboardingPsyche -> R.drawable.play_cat_1024
        ImageId.OnboardingHealth -> R.drawable.bury_cat_1024
        ImageId.OnboardingIllness -> R.drawable.heal_cat_1024
        ImageId.OnboardingCleanUp -> R.drawable.clean_up_cat_1024
        ImageId.OnboardingTalk -> R.drawable.speak_cat_1024
        ImageId.OnboardingAge -> R.drawable.catus_egg
        ImageId.OnboardingGoodLuck -> R.drawable.user_profile_avatar
        ImageId.CatAdultActive -> R.drawable.catus_adult_active
        ImageId.CatAdultDead -> R.drawable.catus_adult_dead
        ImageId.CatAdultDnd -> R.drawable.catus_adult_dnd
        ImageId.CatAdultHungry -> R.drawable.catus_adult_hungry
        ImageId.CatAdultIll -> R.drawable.catus_adult_ill
        ImageId.CatAdultPoop -> R.drawable.catus_adult_poop
        ImageId.CatAdultSleep -> R.drawable.catus_adult_sleep
        ImageId.CatAdultZombie -> R.drawable.catus_adult_zombie
        ImageId.CatEgg -> R.drawable.catus_egg
        ImageId.CatGrave -> R.drawable.catus_grave
        ImageId.CatNewbornActive -> R.drawable.catus_newborn_active
        ImageId.CatNewbornDead -> R.drawable.catus_newborn_dead
        ImageId.CatNewbornDnd -> R.drawable.catus_newborn_dnd
        ImageId.CatNewbornHungry -> R.drawable.catus_newborn_hungry
        ImageId.CatNewbornIll -> R.drawable.catus_newborn_ill
        ImageId.CatNewbornPoop -> R.drawable.catus_newborn_poop
        ImageId.CatNewbornSleep -> R.drawable.catus_newborn_sleep
        ImageId.CatNewbornZombie -> R.drawable.catus_newborn_zombie
        ImageId.CatOldActive -> R.drawable.catus_old_active
        ImageId.CatOldDead -> R.drawable.catus_old_dead
        ImageId.CatOldDnd -> R.drawable.catus_old_dnd
        ImageId.CatOldHungry -> R.drawable.catus_old_hungry
        ImageId.CatOldIll -> R.drawable.catus_old_ill
        ImageId.CatOldPoop -> R.drawable.catus_old_poop
        ImageId.CatOldSleep -> R.drawable.catus_old_sleep
        ImageId.CatOldZombie -> R.drawable.catus_old_zombie
        ImageId.DogAdultActive -> R.drawable.dogus_adult_active
        ImageId.DogAdultDead -> R.drawable.dogus_dead
        ImageId.DogAdultDnd -> R.drawable.dogus_adult_dnd
        ImageId.DogAdultHungry -> R.drawable.dogus_adult_hungry
        ImageId.DogAdultIll -> R.drawable.dogus_adult_ill
        ImageId.DogAdultPoop -> R.drawable.dogus_adult_poop
        ImageId.DogAdultSleep -> R.drawable.dogus_adult_sleep
        ImageId.DogAdultZombie -> R.drawable.dogus_adult_zombie
        ImageId.DogEgg -> R.drawable.dogus_egg
        ImageId.DogGrave -> R.drawable.dogus_grave
        ImageId.DogNewbornActive -> R.drawable.dogus_newborn_active
        ImageId.DogNewbornDead -> R.drawable.dogus_dead
        ImageId.DogNewbornDnd -> R.drawable.dogus_newborn_dnd
        ImageId.DogNewbornHungry -> R.drawable.dogus_newborn_hungry
        ImageId.DogNewbornIll -> R.drawable.dogus_newborn_ill
        ImageId.DogNewbornPoop -> R.drawable.dogus_newborn_poop
        ImageId.DogNewbornSleep -> R.drawable.dogus_newborn_sleep
        ImageId.DogNewbornZombie -> R.drawable.dogus_newborn_zombie
        ImageId.DogOldActive -> R.drawable.dogus_old_active
        ImageId.DogOldDead -> R.drawable.dogus_dead
        ImageId.DogOldDnd -> R.drawable.dogus_old_dnd
        ImageId.DogOldHungry -> R.drawable.dogus_old_hungry
        ImageId.DogOldIll -> R.drawable.dogus_old_ill
        ImageId.DogOldPoop -> R.drawable.dogus_old_poop
        ImageId.DogOldSleep -> R.drawable.dogus_old_sleep
        ImageId.DogOldZombie -> R.drawable.dogus_old_zombie
        ImageId.FrogAdultActive -> R.drawable.frogus_adult_active
        ImageId.FrogAdultDead -> R.drawable.frogus_dead
        ImageId.FrogAdultDnd -> R.drawable.frogus_adult_dnd
        ImageId.FrogAdultHungry -> R.drawable.frogus_adult_hungry
        ImageId.FrogAdultIll -> R.drawable.frogus_adult_ill
        ImageId.FrogAdultPoop -> R.drawable.frogus_adult_poop
        ImageId.FrogAdultSleep -> R.drawable.frogus_adult_sleep
        ImageId.FrogAdultZombie -> R.drawable.frogus_adult_zombie
        ImageId.FrogEgg -> R.drawable.frogus_egg
        ImageId.FrogGrave -> R.drawable.frogus_grave
        ImageId.FrogNewbornActive -> R.drawable.frogus_newborn_active
        ImageId.FrogNewbornDead -> R.drawable.frogus_dead
        ImageId.FrogNewbornDnd -> R.drawable.frogus_newborn_dnd
        ImageId.FrogNewbornHungry -> R.drawable.frogus_newborn_hungry
        ImageId.FrogNewbornIll -> R.drawable.frogus_newborn_ill
        ImageId.FrogNewbornPoop -> R.drawable.frogus_newborn_poop
        ImageId.FrogNewbornSleep -> R.drawable.frogus_newborn_sleep
        ImageId.FrogNewbornZombie -> R.drawable.frogus_newborn_zombie
        ImageId.FrogOldActive -> R.drawable.frogus_old_active
        ImageId.FrogOldDead -> R.drawable.frogus_dead
        ImageId.FrogOldDnd -> R.drawable.frogus_old_dnd
        ImageId.FrogOldHungry -> R.drawable.frogus_old_hungry
        ImageId.FrogOldIll -> R.drawable.frogus_old_ill
        ImageId.FrogOldPoop -> R.drawable.frogus_old_poop
        ImageId.FrogOldSleep -> R.drawable.frogus_old_sleep
        ImageId.FrogOldZombie -> R.drawable.frogus_old_zombie
        ImageId.BoberAdultActive -> R.drawable.bober_adult_active
        ImageId.BoberAdultDead -> R.drawable.bober_adult_dead
        ImageId.BoberAdultDnd -> R.drawable.bober_adult_dnd
        ImageId.BoberAdultHungry -> R.drawable.bober_adult_hungry
        ImageId.BoberAdultIll -> R.drawable.bober_adult_ill
        ImageId.BoberAdultPoop -> R.drawable.bober_adult_poop
        ImageId.BoberAdultSleep -> R.drawable.bober_adult_sleep
        ImageId.BoberAdultZombie -> R.drawable.bober_adult_zombie
        ImageId.BoberGrave -> R.drawable.bober_grave
        ImageId.BoberNewbornActive -> R.drawable.bober_newborn_active
        ImageId.BoberNewbornDead -> R.drawable.bober_newborn_dead
        ImageId.BoberNewbornDnd -> R.drawable.bober_newborn_dnd
        ImageId.BoberNewbornHungry -> R.drawable.bober_newborn_hungry
        ImageId.BoberNewbornIll -> R.drawable.bober_newborn_ill
        ImageId.BoberNewbornPoop -> R.drawable.bober_newborn_poop
        ImageId.BoberNewbornSleep -> R.drawable.bober_newborn_sleep
        ImageId.BoberNewbornZombie -> R.drawable.bober_newborn_zombie
        ImageId.BoberOldActive -> R.drawable.bober_old_active
        ImageId.BoberOldDead -> R.drawable.bober_old_dead
        ImageId.BoberOldDnd -> R.drawable.bober_old_dnd
        ImageId.BoberOldHungry -> R.drawable.bober_old_hungry
        ImageId.BoberOldIll -> R.drawable.bober_old_ill
        ImageId.BoberOldPoop -> R.drawable.bober_old_poop
        ImageId.BoberOldSleep -> R.drawable.bober_old_sleep
        ImageId.BoberOldZombie -> R.drawable.bober_old_zombie
        ImageId.FractalEgg -> R.drawable.fractal_egg
        ImageId.FractalGosperActive -> R.drawable.fractal_gosper_active
        ImageId.FractalGosperHungry -> R.drawable.fractal_gosper_hungry
        ImageId.FractalGosperIll -> R.drawable.fractal_gosper_ill
        ImageId.FractalGosperPoop -> R.drawable.fractal_gosper_poop
        ImageId.FractalGosperSleep -> R.drawable.fractal_gosper_sleep
        ImageId.FractalKochActive -> R.drawable.fractal_koch_active
        ImageId.FractalKochHungry -> R.drawable.fractal_koch_hungry
        ImageId.FractalKochIll -> R.drawable.fractal_koch_ill
        ImageId.FractalKochPoop -> R.drawable.fractal_koch_poop
        ImageId.FractalKochSleep -> R.drawable.fractal_koch_sleep
        ImageId.FractalNewbornActive -> R.drawable.fractal_newborn_active
        ImageId.FractalNewbornHungry -> R.drawable.fractal_newborn_hungry
        ImageId.FractalNewbornIll -> R.drawable.fractal_newborn_ill
        ImageId.FractalNewbornPoop -> R.drawable.fractal_newborn_poop
        ImageId.FractalNewbornSleep -> R.drawable.fractal_newborn_sleep
        ImageId.FractalSpongeActive -> R.drawable.fractal_sponge_active
        ImageId.FractalSpongeHungry -> R.drawable.fractal_sponge_hungry
        ImageId.FractalSpongeIll -> R.drawable.fractal_sponge_ill
        ImageId.FractalSpongePoop -> R.drawable.fractal_sponge_poop
        ImageId.FractalSpongeSleep -> R.drawable.fractal_sponge_sleep
        //region Dragon
        //region Common
        ImageId.DragonGrave -> R.drawable.dragon_grave
        //endregion
        //region Red Dragon
        ImageId.DragonRedAdultActive -> R.drawable.dragon_red_adult_active
        ImageId.DragonRedAdultDead -> R.drawable.dragon_red_adult_dead
        ImageId.DragonRedAdultHungry -> R.drawable.dragon_red_adult_hungry
        ImageId.DragonRedAdultIll -> R.drawable.dragon_red_adult_ill
        ImageId.DragonRedAdultPoop -> R.drawable.dragon_red_adult_poop
        ImageId.DragonRedAdultSleep -> R.drawable.dragon_red_adult_sleep
        ImageId.DragonRedAdultZombie -> R.drawable.dragon_red_adult_zombie
        ImageId.DragonRedNewbornActive -> R.drawable.dragon_red_newborn_active
        ImageId.DragonRedNewbornDead -> R.drawable.dragon_red_newborn_dead
        ImageId.DragonRedNewbornHungry -> R.drawable.dragon_red_newborn_hungry
        ImageId.DragonRedNewbornIll -> R.drawable.dragon_red_newborn_ill
        ImageId.DragonRedNewbornPoop -> R.drawable.dragon_red_newborn_poop
        ImageId.DragonRedNewbornSleep -> R.drawable.dragon_red_newborn_sleep
        ImageId.DragonRedNewbornZombie -> R.drawable.dragon_red_newborn_zombie
        ImageId.DragonRedOldActive -> R.drawable.dragon_red_old_active
        ImageId.DragonRedOldDead -> R.drawable.dragon_red_old_dead
        ImageId.DragonRedOldHungry -> R.drawable.dragon_red_old_hungry
        ImageId.DragonRedOldIll -> R.drawable.dragon_red_old_ill
        ImageId.DragonRedOldPoop -> R.drawable.dragon_red_old_poop
        ImageId.DragonRedOldSleep -> R.drawable.dragon_red_old_sleep
        ImageId.DragonRedOldZombie -> R.drawable.dragon_red_old_zombie
        //endregion
        //region Blue Dragon
        ImageId.DragonBlueAdultActive -> R.drawable.dragon_blue_adult_active
        ImageId.DragonBlueAdultDead -> R.drawable.dragon_blue_adult_dead
        ImageId.DragonBlueAdultHungry -> R.drawable.dragon_blue_adult_hungry
        ImageId.DragonBlueAdultIll -> R.drawable.dragon_blue_adult_ill
        ImageId.DragonBlueAdultPoop -> R.drawable.dragon_blue_adult_poop
        ImageId.DragonBlueAdultSleep -> R.drawable.dragon_blue_adult_sleep
        ImageId.DragonBlueAdultZombie -> R.drawable.dragon_blue_adult_zombie
        ImageId.DragonBlueNewbornActive -> R.drawable.dragon_blue_newborn_active
        ImageId.DragonBlueNewbornDead -> R.drawable.dragon_blue_newborn_dead
        ImageId.DragonBlueNewbornHungry -> R.drawable.dragon_blue_newborn_hungry
        ImageId.DragonBlueNewbornIll -> R.drawable.dragon_blue_newborn_ill
        ImageId.DragonBlueNewbornPoop -> R.drawable.dragon_blue_newborn_poop
        ImageId.DragonBlueNewbornSleep -> R.drawable.dragon_blue_newborn_sleep
        ImageId.DragonBlueNewbornZombie -> R.drawable.dragon_blue_newborn_zombie
        ImageId.DragonBlueOldActive -> R.drawable.dragon_blue_old_active
        ImageId.DragonBlueOldDead -> R.drawable.dragon_blue_old_dead
        ImageId.DragonBlueOldHungry -> R.drawable.dragon_blue_old_hungry
        ImageId.DragonBlueOldIll -> R.drawable.dragon_blue_old_ill
        ImageId.DragonBlueOldPoop -> R.drawable.dragon_blue_old_poop
        ImageId.DragonBlueOldSleep -> R.drawable.dragon_blue_old_sleep
        ImageId.DragonBlueOldZombie -> R.drawable.dragon_blue_old_zombie
        //endregion
        //region Void Dragon
        ImageId.DragonVoidAdultActive -> R.drawable.dragon_void_adult_active
        ImageId.DragonVoidAdultDead -> R.drawable.dragon_void_adult_dead
        ImageId.DragonVoidAdultHungry -> R.drawable.dragon_void_adult_hungry
        ImageId.DragonVoidAdultIll -> R.drawable.dragon_void_adult_ill
        ImageId.DragonVoidAdultPoop -> R.drawable.dragon_void_adult_poop
        ImageId.DragonVoidAdultSleep -> R.drawable.dragon_void_adult_sleep
        ImageId.DragonVoidAdultZombie -> R.drawable.dragon_void_adult_zombie
        ImageId.DragonVoidNewbornActive -> R.drawable.dragon_void_newborn_active
        ImageId.DragonVoidNewbornDead -> R.drawable.dragon_void_newborn_dead
        ImageId.DragonVoidNewbornHungry -> R.drawable.dragon_void_newborn_hungry
        ImageId.DragonVoidNewbornIll -> R.drawable.dragon_void_newborn_ill
        ImageId.DragonVoidNewbornPoop -> R.drawable.dragon_void_newborn_poop
        ImageId.DragonVoidNewbornSleep -> R.drawable.dragon_void_newborn_sleep
        ImageId.DragonVoidNewbornZombie -> R.drawable.dragon_void_newborn_zombie
        ImageId.DragonVoidOldActive -> R.drawable.dragon_void_old_active
        ImageId.DragonVoidOldDead -> R.drawable.dragon_void_old_dead
        ImageId.DragonVoidOldHungry -> R.drawable.dragon_void_old_hungry
        ImageId.DragonVoidOldIll -> R.drawable.dragon_void_old_ill
        ImageId.DragonVoidOldPoop -> R.drawable.dragon_void_old_poop
        ImageId.DragonVoidOldSleep -> R.drawable.dragon_void_old_sleep
        ImageId.DragonVoidOldZombie -> R.drawable.dragon_void_old_zombie
        //endregion
        //endregion
        ImageId.DugOutGrave -> R.drawable.dug_out_grave
        ImageId.UserProfileAvatar -> R.drawable.user_profile_avatar
        //region Items
        ImageId.Necronomicon -> R.drawable.item_necronomicon
        ImageId.PieceOfCloth -> R.drawable.item_piece_of_cloth
        ImageId.MysteriousBook -> R.drawable.item_mysterious_book
        ImageId.Fish -> R.drawable.item_fish
        ImageId.FrogusEgg -> R.drawable.frogus_egg
        ImageId.DogusEgg -> R.drawable.dogus_egg
        ImageId.CatusEgg -> R.drawable.catus_egg
        ImageId.BoberEgg -> R.drawable.bober_egg
        ImageId.DragonEgg -> R.drawable.dragon_egg
        ImageId.Basket -> R.drawable.item_basket
        ImageId.TwoMeterRuler -> R.drawable.item_two_meter_ruler
        ImageId.TenCentimeterRuler -> R.drawable.item_ten_centimeter_ruler
        ImageId.MathBook -> R.drawable.item_math_book
        ImageId.MemoryOfMage -> R.drawable.item_memory_of_mage
        ImageId.MemoryOfWarrior -> R.drawable.item_memory_of_warrior
        ImageId.MemoryOfBard -> R.drawable.item_memory_of_bard
        ImageId.MemoryOfSmith -> R.drawable.item_memory_of_smith
        ImageId.CurseOfMage -> R.drawable.item_curse_of_mage
        ImageId.CurseOfWarrior -> R.drawable.item_curse_of_warrior
        ImageId.CurseOfBard -> R.drawable.item_curse_of_bard
        ImageId.CurseOfSmith -> R.drawable.item_curse_of_smith
        //endregion
    }
}
