package bav.petus.android.ui.common

import bav.petus.android.R
import bav.petus.core.resources.StringId

fun StringId.toResId(): Int {
    return when (this) {
        StringId.ZooScreenTitle -> R.string.ZooScreenTitle
        StringId.CemeteryScreenTitle -> R.string.CemeteryScreenTitle
        StringId.ProfileScreenTitle -> R.string.ProfileScreenTitle
        StringId.WeatherScreenTitle -> R.string.WeatherScreenTitle
        StringId.QuestsScreenTitle -> R.string.QuestsScreenTitle
        StringId.PetTypeDescriptionCatus -> R.string.PetTypeDescriptionCatus
        StringId.PetTypeDescriptionDogus -> R.string.PetTypeDescriptionDogus
        StringId.PetTypeDescriptionFrogus -> R.string.PetTypeDescriptionFrogus
        StringId.PetTypeDescriptionBober -> R.string.PetTypeDescriptionBober
        StringId.PetTypeDescriptionFractal -> R.string.PetTypeDescriptionFractal
        StringId.PetTypeDescriptionDragon -> R.string.PetTypeDescriptionDragon
        StringId.WhatIsGoingOnWithYou -> R.string.WhatIsGoingOnWithYou
        StringId.WhatIsGoingOnWithYouLatin -> R.string.WhatIsGoingOnWithYouLatin
        StringId.WhatIsGoingOnWithYouPolish -> R.string.WhatIsGoingOnWithYouPolish
        StringId.WhatIsGoingOnWithYouMathMandelbrot -> R.string.WhatIsGoingOnWithYouMathMandelbrot
        StringId.WhatIsGoingOnWithYouMathGosper -> R.string.WhatIsGoingOnWithYouMathGosper
        StringId.WhatIsGoingOnWithYouMathKoch -> R.string.WhatIsGoingOnWithYouMathKoch
        StringId.WhatIsGoingOnWithYouMathSponge -> R.string.WhatIsGoingOnWithYouMathSponge
        StringId.BeingBetter -> R.string.BeenBetter
        StringId.IShouldGo -> R.string.IShouldGo
        StringId.SeeYa -> R.string.SeeYa
        StringId.ByeBye -> R.string.ByeBye
        StringId.Sure -> R.string.Sure
        StringId.Ok -> R.string.Ok
        StringId.AllRight -> R.string.AllRight
        StringId.Excellent -> R.string.Excellent
        StringId.Ellipsis -> R.string.Ellipsis
        StringId.Thanks -> R.string.Thanks
        StringId.Use -> R.string.Use
        StringId.Destroy -> R.string.Destroy
        StringId.IAmOkayHowAreYou -> R.string.IAmOkayHowAreYou
        StringId.IAmSick -> R.string.IAmSick
        StringId.IAmSickLatin -> R.string.IAmSickLatin
        StringId.IAmSickPolish -> R.string.IAmSickPolish
        StringId.IAmSickMath -> R.string.IAmSickMath
        StringId.IAmHungry -> R.string.IAmHungry
        StringId.IAmHungryLatin -> R.string.IAmHungryLatin
        StringId.IAmHungryPolish -> R.string.IAmHungryPolish
        StringId.IAmHungryMath -> R.string.IAmHungryMath
        StringId.IPooped -> R.string.IPooped
        StringId.IPoopedLatin -> R.string.IPoopedLatin
        StringId.IPoopedPolish -> R.string.IPoopedPolish
        StringId.IPoopedMath -> R.string.IPoopedMath
        StringId.IAmBored -> R.string.IAmBored
        StringId.IAmBoredLatin -> R.string.IAmBoredLatin
        StringId.IAmBoredPolish -> R.string.IAmBoredPolish
        StringId.IAmBoredMath -> R.string.IAmBoredMath
        StringId.IAmStillAngryAfterForceWakeUp -> R.string.IAmStillAngryAfterForceWakeUp
        StringId.IAmStillAngryAfterForceWakeUpLatin -> R.string.IAmStillAngryAfterForceWakeUpLatin
        StringId.IAmStillAngryAfterForceWakeUpPolish -> R.string.IAmStillAngryAfterForceWakeUpPolish
        StringId.IAmStillAngryAfterForceWakeUpMath -> R.string.IAmStillAngryAfterForceWakeUpMath
        StringId.IAmHalfHp -> R.string.IAmHalfHp
        StringId.IAmHalfHpLatin -> R.string.IAmHalfHpLatin
        StringId.IAmHalfHpPolish -> R.string.IAmHalfHpPolish
        StringId.IAmHalfHpMath -> R.string.IAmHalfHpMath
        StringId.IAmGood -> R.string.IAmGood
        StringId.IAmGoodLatin -> R.string.IAmGoodLatin
        StringId.IAmGoodPolish -> R.string.IAmGoodPolish
        StringId.IAmGoodMath -> R.string.IAmGoodMath
        is StringId.IWillDie -> error("IWillDie requires formatting and should not be mapped with toResId()")
        is StringId.IWillDieLatin -> error("IWillDieLatin requires formatting and should not be mapped with toResId()")
        is StringId.IWillDiePolish -> error("IWillDiePolish requires formatting and should not be mapped with toResId()")
        StringId.QuestResetAnswer0 -> R.string.QuestResetAnswer0
        StringId.QuestResetDialog0 -> R.string.QuestResetDialog0
        StringId.QuestResetAnswer1 -> R.string.QuestResetAnswer1
        StringId.QuestResetDialog1 -> R.string.QuestResetDialog1
        StringId.NecronomiconStage3AnswerOption0 -> R.string.NecronomiconStage3AnswerOption0
        StringId.NecronomiconStage3CommonDialog -> R.string.NecronomiconStage3CommonDialog
        StringId.NecronomiconStage3DogDialog -> R.string.NecronomiconStage3DogDialog
        StringId.NecronomiconStage3DogDialogAnswerOption0 -> R.string.NecronomiconStage3DogDialogAnswerOption0
        StringId.NecronomiconStage5AnswerOption0 -> R.string.NecronomiconStage5AnswerOption0
        StringId.NecronomiconStage5DogDialog -> R.string.NecronomiconStage5DogDialog
        StringId.NecronomiconStage6AnswerOption0 -> R.string.NecronomiconStage6AnswerOption0
        StringId.NecronomiconStage6DogDialog -> R.string.NecronomiconStage6DogDialog
        StringId.NecronomiconStage7DogDialog0 -> R.string.NecronomiconStage7DogDialog0
        StringId.NecronomiconStage7AnswerOption0 -> R.string.NecronomiconStage7AnswerOption0
        StringId.NecronomiconStage7DogDialog1 -> R.string.NecronomiconStage7DogDialog1
        StringId.NecronomiconStage7DogDialog2 -> R.string.NecronomiconStage7DogDialog2
        StringId.NecronomiconStage8AnswerOption0 -> R.string.NecronomiconStage8AnswerOption0
        StringId.NecronomiconStage8Dialog0 -> R.string.NecronomiconStage8Dialog0
        StringId.NecronomiconStage8Dialog1 -> R.string.NecronomiconStage8Dialog1
        StringId.MysteriousBook -> R.string.MysteriousBook
        StringId.Necronomicon -> R.string.Necronomicon
        StringId.PieceOfCloth -> R.string.PieceOfCloth
        StringId.Fish -> R.string.Fish
        StringId.FrogusEgg -> R.string.FrogusEgg
        StringId.DogusEgg -> R.string.DogusEgg
        StringId.CatusEgg -> R.string.CatusEgg
        StringId.BoberEgg -> R.string.BoberEgg
        StringId.DragonEgg -> R.string.DragonEgg
        StringId.Basket -> R.string.Basket
        StringId.TwoMeterRuler -> R.string.TwoMeterRuler
        StringId.TenCentimeterRuler -> R.string.TenCentimeterRuler
        StringId.MathBook -> R.string.MathBook
        StringId.MemoryOfMage -> R.string.MemoryOfMage
        StringId.MemoryOfWarrior -> R.string.MemoryOfWarrior
        StringId.MemoryOfBard -> R.string.MemoryOfBard
        StringId.MemoryOfSmith -> R.string.MemoryOfSmith
        StringId.CurseOfMage -> R.string.CurseOfMage
        StringId.CurseOfWarrior -> R.string.CurseOfWarrior
        StringId.CurseOfBard -> R.string.CurseOfBard
        StringId.CurseOfSmith -> R.string.CurseOfSmith
        StringId.MeditationExerciseBreathAwareness -> R.string.MeditationExerciseBreathAwareness
        StringId.MeditationExerciseBoxBreathing -> R.string.MeditationExerciseBoxBreathing
        StringId.MeditationExerciseBodyScan -> R.string.MeditationExerciseBodyScan
        StringId.MeditationExerciseLovingKindnessPhrases -> R.string.MeditationExerciseLovingKindnessPhrases
        StringId.MeditationExerciseCountingTheBreath -> R.string.MeditationExerciseCountingTheBreath
        StringId.MeditationExerciseMantraRepetition -> R.string.MeditationExerciseMantraRepetition
        StringId.MeditationExerciseWalkingMeditation -> R.string.MeditationExerciseWalkingMeditation
        StringId.MeditationExerciseCandleGazing -> R.string.MeditationExerciseCandleGazing
        StringId.MeditationExerciseNotingPractice -> R.string.MeditationExerciseNotingPractice
        StringId.MeditationExerciseFiveSensesAwareness -> R.string.MeditationExerciseFiveSensesAwareness
        StringId.MeditationExerciseVisualization -> R.string.MeditationExerciseVisualization
        StringId.MeditationExerciseMountainMeditation -> R.string.MeditationExerciseMountainMeditation
        StringId.MeditationExerciseSoundAwareness -> R.string.MeditationExerciseSoundAwareness
        StringId.MeditationExerciseTonglenExercise -> R.string.MeditationExerciseTonglenExercise
        StringId.MeditationExerciseGratitudeReflection -> R.string.MeditationExerciseGratitudeReflection
        StringId.MeditationExerciseMindfulEating -> R.string.MeditationExerciseMindfulEating
        StringId.MeditationExerciseProgressiveRelaxation -> R.string.MeditationExerciseProgressiveRelaxation
        StringId.MeditationExerciseChakraFocusing -> R.string.MeditationExerciseChakraFocusing
        StringId.MeditationExerciseSelfInquiryQuestions -> R.string.MeditationExerciseSelfInquiryQuestions
        StringId.MeditationExerciseSilentSitting -> R.string.MeditationExerciseSilentSitting
        StringId.OnboardingHomeTitle -> R.string.OnboardingHomeTitle
        StringId.OnboardingHomeMessage -> R.string.OnboardingHomeMessage
        StringId.OnboardingSatietyTitle -> R.string.OnboardingSatietyTitle
        StringId.OnboardingSatietyMessage -> R.string.OnboardingSatietyMessage
        StringId.OnboardingPsycheTitle -> R.string.OnboardingPsycheTitle
        StringId.OnboardingPsycheMessage -> R.string.OnboardingPsycheMessage
        StringId.OnboardingHealthTitle -> R.string.OnboardingHealthTitle
        StringId.OnboardingHealthMessage -> R.string.OnboardingHealthMessage
        StringId.OnboardingIllnessTitle -> R.string.OnboardingIllnessTitle
        StringId.OnboardingIllnessMessage -> R.string.OnboardingIllnessMessage
        StringId.OnboardingCleanUpTitle -> R.string.OnboardingCleanUpTitle
        StringId.OnboardingCleanUpMessage -> R.string.OnboardingCleanUpMessage
        StringId.OnboardingTalkTitle -> R.string.OnboardingTalkTitle
        StringId.OnboardingTalkMessage -> R.string.OnboardingTalkMessage
        StringId.OnboardingAgeTitle -> R.string.OnboardingAgeTitle
        StringId.OnboardingAgeMessage -> R.string.OnboardingAgeMessage
        StringId.OnboardingGoodLuckTitle -> R.string.OnboardingGoodLuckTitle
        StringId.OnboardingGoodLuckMessage -> R.string.OnboardingGoodLuckMessage
        StringId.OnboardingSkipTitle -> R.string.OnboardingSkipTitle
        StringId.OnboardingPreviousTitle -> R.string.OnboardingPreviousTitle
        StringId.OnboardingNextTitle -> R.string.OnboardingNextTitle
        StringId.OnboardingLetsGoTitle -> R.string.OnboardingLetsGoTitle
        StringId.OnboardingHowToButtonTitle -> R.string.OnboardingHowToButtonTitle
        StringId.HistoryEventPetBecomeAdult -> R.string.HistoryEventPetBecomeAdult
        StringId.HistoryEventPetBecomeNewborn -> R.string.HistoryEventPetBecomeNewborn
        StringId.HistoryEventPetBecomeOld -> R.string.HistoryEventPetBecomeOld
        StringId.HistoryEventPetBecomeTeen -> R.string.HistoryEventPetBecomeTeen
        StringId.HistoryEventPetBuried -> R.string.HistoryEventPetBuried
        StringId.HistoryEventPetForgotten -> R.string.HistoryEventPetForgotten
        StringId.HistoryEventPetCleanUp -> R.string.HistoryEventPetCleanUp
        StringId.HistoryEventPetCreated -> R.string.HistoryEventPetCreated
        StringId.HistoryEventPetDied -> R.string.HistoryEventPetDied
        StringId.HistoryEventPetFeed -> R.string.HistoryEventPetFeed
        StringId.HistoryEventPetForciblyWakeUp -> R.string.HistoryEventPetForciblyWakeUp
        StringId.HistoryEventPetGetHealed -> R.string.HistoryEventPetGetHealed
        StringId.HistoryEventPetGetIll -> R.string.HistoryEventPetGetIll
        StringId.HistoryEventPetPlay -> R.string.HistoryEventPetPlay
        StringId.HistoryEventPetPoop -> R.string.HistoryEventPetPoop
        StringId.HistoryEventPetResurrected -> R.string.HistoryEventPetResurrected
        StringId.HistoryEventPetSleep -> R.string.HistoryEventPetSleep
        StringId.HistoryEventPetWakeUp -> R.string.HistoryEventPetWakeUp
        StringId.Necromancy -> R.string.Necromancy
        StringId.Meditation -> R.string.Meditation
        StringId.ObtainFrogusStage1Answer0 -> R.string.ObtainFrogusStage1Answer0
        StringId.ObtainFrogusStage1Dialog0 -> R.string.ObtainFrogusStage1Dialog0
        StringId.ObtainFrogusStage1Answer1 -> R.string.ObtainFrogusStage1Answer1
        StringId.ObtainFrogusStage3Answer0 -> R.string.ObtainFrogusStage3Answer0
        StringId.ObtainFrogusStage3Dialog0 -> R.string.ObtainFrogusStage3Dialog0
        StringId.ObtainFrogusStage3Answer1 -> R.string.ObtainFrogusStage3Answer1
        StringId.ObtainFrogusStage5Answer0 -> R.string.ObtainFrogusStage5Answer0
        StringId.ObtainFrogusStage5Dialog0 -> R.string.ObtainFrogusStage5Dialog0
        StringId.ObtainFrogusStage5Answer1 -> R.string.ObtainFrogusStage5Answer1
        StringId.ObtainBoberStage2Answer0 -> R.string.ObtainBoberStage2Answer0
        StringId.ObtainBoberStage2Answer1 -> R.string.ObtainBoberStage2Answer1
        StringId.ObtainBoberStage2Dialog0 -> R.string.ObtainBoberStage2Dialog0
        StringId.ObtainBoberStage2Dialog1 -> R.string.ObtainBoberStage2Dialog1
        StringId.ObtainBoberStage3Answer0 -> R.string.ObtainBoberStage3Answer0
        StringId.ObtainBoberStage3Dialog0 -> R.string.ObtainBoberStage3Dialog0
        StringId.ObtainBoberStage4Dialog0 -> R.string.ObtainBoberStage4Dialog0
        StringId.ObtainBoberStage6Answer0 -> R.string.ObtainBoberStage6Answer0
        StringId.ObtainBoberStage6Dialog0 -> R.string.ObtainBoberStage6Dialog0
        StringId.ObtainBoberStage6Dialog1 -> R.string.ObtainBoberStage6Dialog1
        StringId.ObtainBoberStage8Answer0 -> R.string.ObtainBoberStage8Answer0
        StringId.ObtainBoberStage8Dialog0 -> R.string.ObtainBoberStage8Dialog0
        StringId.ObtainBoberStage9Answer0 -> R.string.ObtainBoberStage9Answer0
        StringId.ObtainBoberStage9Dialog0 -> R.string.ObtainBoberStage9Dialog0
        StringId.ObtainBoberStage9Dialog1 -> R.string.ObtainBoberStage9Dialog1
        StringId.ObtainBoberStage9Dialog2 -> R.string.ObtainBoberStage9Dialog2
        StringId.ObtainBoberStage10Answer0 -> R.string.ObtainBoberStage10Answer0
        StringId.ObtainBoberStage10Dialog0 -> R.string.ObtainBoberStage10Dialog0
        StringId.ObtainBoberStage11Dialog0 -> R.string.ObtainBoberStage11Dialog0
        StringId.ObtainBoberStage11Answer0 -> R.string.ObtainBoberStage11Answer0
        StringId.ObtainFractalStage1Answer0 -> R.string.ObtainFractalStage1Answer0
        StringId.ObtainFractalStage1Dialog0 -> R.string.ObtainFractalStage1Dialog0
        StringId.ObtainFractalStage1Dialog1 -> R.string.ObtainFractalStage1Dialog1
        StringId.ObtainFractalStage1Answer1 -> R.string.ObtainFractalStage1Answer1
        StringId.ObtainFractalStage3Answer0 -> R.string.ObtainFractalStage3Answer0
        StringId.ObtainFractalStage3Dialog0 -> R.string.ObtainFractalStage3Dialog0
        StringId.ObtainFractalStage3Answer1 -> R.string.ObtainFractalStage3Answer1
        StringId.ObtainFractalStage5Answer0 -> R.string.ObtainFractalStage5Answer0
        StringId.ObtainFractalStage5Dialog0 -> R.string.ObtainFractalStage5Dialog0
        StringId.ObtainFractalStage5Answer1 -> R.string.ObtainFractalStage5Answer1
        StringId.ObtainFractalStage6Answer0 -> R.string.ObtainFractalStage6Answer0
        StringId.ObtainFractalStage6Dialog0 -> R.string.ObtainFractalStage6Dialog0
        StringId.ObtainFractalStage6Answer1 -> R.string.ObtainFractalStage6Answer1
        StringId.MeditationStage1Answer0 -> R.string.MeditationStage1Answer0
        StringId.MeditationStage1Dialog0 -> R.string.MeditationStage1Dialog0
        StringId.MeditationStage1Dialog1 -> R.string.MeditationStage1Dialog1
        StringId.MeditationStage1Answer1 -> R.string.MeditationStage1Answer1
        StringId.MeditationStage2Answer0 -> R.string.MeditationStage2Answer0
        StringId.MeditationStage2Dialog0 -> R.string.MeditationStage2Dialog0
        StringId.MeditationStage2Dialog1 -> R.string.MeditationStage2Dialog1
        StringId.MeditationStage2Dialog2 -> R.string.MeditationStage2Dialog2
        StringId.MeditationStage3Answer0 -> R.string.MeditationStage3Answer0
        StringId.MeditationStage3Dialog0 -> R.string.MeditationStage3Dialog0
        StringId.MeditationStage3Dialog1 -> R.string.MeditationStage3Dialog1
        StringId.MeditationStage3Dialog2 -> R.string.MeditationStage3Dialog2
        StringId.MeditationStage3Answer1 -> R.string.MeditationStage3Answer1
        StringId.MeditationStage3Dialog4 -> R.string.MeditationStage3Dialog4
        StringId.MeditationStage3Answer2 -> R.string.MeditationStage3Answer2
        StringId.ObtainDragonStage1Answer0 -> R.string.ObtainDragonStage1Answer0
        StringId.ObtainDragonStage1Dialog0 -> R.string.ObtainDragonStage1Dialog0
        StringId.ObtainDragonStage1Answer1 -> R.string.ObtainDragonStage1Answer1
        StringId.ObtainDragonStage1Dialog1 -> R.string.ObtainDragonStage1Dialog1
        StringId.ObtainDragonStage1Answer2 -> R.string.ObtainDragonStage1Answer2
        StringId.ObtainDragonStage1Dialog2 -> R.string.ObtainDragonStage1Dialog2
        StringId.ObtainDragonStage1Answer3 -> R.string.ObtainDragonStage1Answer3
        StringId.ObtainDragonStage2Answer0 -> R.string.ObtainDragonStage2Answer0
        StringId.ObtainDragonStage2Dialog0 -> R.string.ObtainDragonStage2Dialog0
        StringId.ObtainDragonStage2Answer1 -> R.string.ObtainDragonStage2Answer1
        StringId.ObtainDragonStage2Answer2 -> R.string.ObtainDragonStage2Answer2
        StringId.ObtainDragonStage2Dialog1 -> R.string.ObtainDragonStage2Dialog1
        StringId.ObtainDragonStage2Answer3 -> R.string.ObtainDragonStage2Answer3
        StringId.ObtainDragonStage2Dialog2 -> R.string.ObtainDragonStage2Dialog2
        StringId.ObtainDragonStage2Answer4 -> R.string.ObtainDragonStage2Answer4
        StringId.ObtainDragonStage2Dialog3 -> R.string.ObtainDragonStage2Dialog3
        StringId.ObtainDragonStage2Answer5 -> R.string.ObtainDragonStage2Answer5
        StringId.ObtainDragonStage3Answer0 -> R.string.ObtainDragonStage3Answer0
        StringId.ObtainDragonStage3Dialog0 -> R.string.ObtainDragonStage3Dialog0
        StringId.ObtainDragonStage4Answer0 -> R.string.ObtainDragonStage4Answer0
        StringId.ObtainDragonStage4Dialog0 -> R.string.ObtainDragonStage4Dialog0
        StringId.ObtainDragonStage4Dialog1 -> R.string.ObtainDragonStage4Dialog1
        StringId.ObtainDragonStage4Dialog2 -> R.string.ObtainDragonStage4Dialog2
        StringId.ObtainDragonStage5Answer0 -> R.string.ObtainDragonStage5Answer0
        StringId.ObtainDragonStage5Dialog0 -> R.string.ObtainDragonStage5Dialog0
        StringId.ObtainDragonStage5Dialog1 -> R.string.ObtainDragonStage5Dialog1
        StringId.ObtainDragonStage5Dialog2 -> R.string.ObtainDragonStage5Dialog2
        StringId.ObtainDragonStage5Dialog3 -> R.string.ObtainDragonStage5Dialog3
        StringId.ObtainDragonStage5Answer1 -> R.string.ObtainDragonStage5Answer1
        StringId.ObtainDragonStage5Dialog4 -> R.string.ObtainDragonStage5Dialog4
        StringId.ObtainDragonStage5Answer2 -> R.string.ObtainDragonStage5Answer2
        StringId.ObtainDragonStage5Answer3 -> R.string.ObtainDragonStage5Answer3
        StringId.ObtainDragonStage5Answer4 -> R.string.ObtainDragonStage5Answer4
        StringId.ObtainDragonStage5Answer5 -> R.string.ObtainDragonStage5Answer5
        StringId.ObtainDragonStage5Answer6 -> R.string.ObtainDragonStage5Answer6
        StringId.ObtainDragonStage5Dialog5 -> R.string.ObtainDragonStage5Dialog5
        StringId.ObtainDragonStage7Answer0 -> R.string.ObtainDragonStage7Answer0
        StringId.ObtainDragonStage7Dialog0 -> R.string.ObtainDragonStage7Dialog0
        StringId.ObtainDragonStage7Dialog1 -> R.string.ObtainDragonStage7Dialog1
        StringId.ObtainDragonStage7Dialog2 -> R.string.ObtainDragonStage7Dialog2
        StringId.ObtainDragonStage7Dialog3 -> R.string.ObtainDragonStage7Dialog3
        StringId.ObtainDragonStage8Answer0 -> R.string.ObtainDragonStage8Answer0
        StringId.ObtainDragonStage9Answer0 -> R.string.ObtainDragonStage9Answer0
        StringId.ObtainDragonStage9Dialog0 -> R.string.ObtainDragonStage9Dialog0
        StringId.ObtainDragonStage9Dialog1 -> R.string.ObtainDragonStage9Dialog1
        StringId.ObtainDragonStage9Dialog2 -> R.string.ObtainDragonStage9Dialog2
        StringId.ObtainDragonStage10Answer0 -> R.string.ObtainDragonStage10Answer0
        StringId.ObtainDragonStage10Answer1 -> R.string.ObtainDragonStage10Answer1
        StringId.ObtainDragonStage10Dialog0 -> R.string.ObtainDragonStage10Dialog0
        StringId.ObtainDragonStage10Dialog1 -> R.string.ObtainDragonStage10Dialog1
        StringId.ObtainDragonStage10Dialog2 -> R.string.ObtainDragonStage10Dialog2
        StringId.ObtainDragonStage10Dialog3 -> R.string.ObtainDragonStage10Dialog3
        StringId.ObtainDragonStage12Answer0 -> R.string.ObtainDragonStage12Answer0
        StringId.ObtainDragonStage12Dialog0 -> R.string.ObtainDragonStage12Dialog0
        StringId.ObtainDragonStage12Dialog1 -> R.string.ObtainDragonStage12Dialog1
        StringId.ObtainDragonStage12Dialog2 -> R.string.ObtainDragonStage12Dialog2
        StringId.ObtainDragonStage12Dialog3 -> R.string.ObtainDragonStage12Dialog3
        StringId.ObtainDragonStage13Answer0 -> R.string.ObtainDragonStage13Answer0
        StringId.ObtainDragonStage14Answer0 -> R.string.ObtainDragonStage14Answer0
        StringId.ObtainDragonStage14Dialog0 -> R.string.ObtainDragonStage14Dialog0
        StringId.ObtainDragonStage14Dialog1 -> R.string.ObtainDragonStage14Dialog1
        StringId.ObtainDragonStage14Dialog2 -> R.string.ObtainDragonStage14Dialog2
        StringId.ObtainDragonStage15Answer0 -> R.string.ObtainDragonStage15Answer0
        StringId.ObtainDragonStage15Answer1 -> R.string.ObtainDragonStage15Answer1
        StringId.ObtainDragonStage15Dialog0 -> R.string.ObtainDragonStage15Dialog0
        StringId.ObtainDragonStage15Dialog1 -> R.string.ObtainDragonStage15Dialog1
        StringId.ObtainDragonStage15Dialog2 -> R.string.ObtainDragonStage15Dialog2
        StringId.ObtainDragonStage15Dialog3 -> R.string.ObtainDragonStage15Dialog3
        StringId.ObtainDragonStage17Answer0 -> R.string.ObtainDragonStage17Answer0
        StringId.ObtainDragonStage17Dialog0 -> R.string.ObtainDragonStage17Dialog0
        StringId.ObtainDragonStage17Dialog1 -> R.string.ObtainDragonStage17Dialog1
        StringId.ObtainDragonStage17Dialog2 -> R.string.ObtainDragonStage17Dialog2
        StringId.ObtainDragonStage17Dialog3 -> R.string.ObtainDragonStage17Dialog3
        StringId.ObtainDragonStage18Answer0 -> R.string.ObtainDragonStage18Answer0
        StringId.ObtainDragonStage19Answer0 -> R.string.ObtainDragonStage19Answer0
        StringId.ObtainDragonStage19Dialog0 -> R.string.ObtainDragonStage19Dialog0
        StringId.ObtainDragonStage19Dialog1 -> R.string.ObtainDragonStage19Dialog1
        StringId.ObtainDragonStage19Dialog2 -> R.string.ObtainDragonStage19Dialog2
        StringId.ObtainDragonStage20Answer0 -> R.string.ObtainDragonStage20Answer0
        StringId.ObtainDragonStage20Answer1 -> R.string.ObtainDragonStage20Answer1
        StringId.ObtainDragonStage20Dialog0 -> R.string.ObtainDragonStage20Dialog0
        StringId.ObtainDragonStage20Dialog1 -> R.string.ObtainDragonStage20Dialog1
        StringId.ObtainDragonStage20Dialog2 -> R.string.ObtainDragonStage20Dialog2
        StringId.ObtainDragonStage20Dialog3 -> R.string.ObtainDragonStage20Dialog3
        StringId.ObtainDragonStage22Answer0 -> R.string.ObtainDragonStage22Answer0
        StringId.ObtainDragonStage22Dialog0 -> R.string.ObtainDragonStage22Dialog0
        StringId.ObtainDragonStage22Dialog1 -> R.string.ObtainDragonStage22Dialog1
        StringId.ObtainDragonStage22Dialog2 -> R.string.ObtainDragonStage22Dialog2
        StringId.ObtainDragonStage22Dialog3 -> R.string.ObtainDragonStage22Dialog3
        StringId.ObtainDragonStage23Answer0 -> R.string.ObtainDragonStage23Answer0
        StringId.ObtainDragonStage24Answer0 -> R.string.ObtainDragonStage24Answer0
        StringId.ObtainDragonStage24Dialog0 -> R.string.ObtainDragonStage24Dialog0
        StringId.ObtainDragonStage24Dialog1 -> R.string.ObtainDragonStage24Dialog1
        StringId.ObtainDragonStage24Dialog2 -> R.string.ObtainDragonStage24Dialog2
        StringId.ObtainDragonStage24Dialog3 -> R.string.ObtainDragonStage24Dialog3
        StringId.ObtainDragonStage24Answer1 -> R.string.ObtainDragonStage24Answer1
        StringId.ObtainDragonStage24Dialog7 -> R.string.ObtainDragonStage24Dialog7
        StringId.ObtainDragonStage25Answer0 -> R.string.ObtainDragonStage25Answer0
        StringId.ObtainDragonStage25Answer1 -> R.string.ObtainDragonStage25Answer1
        StringId.ObtainDragonStage25Dialog0 -> R.string.ObtainDragonStage25Dialog0
        StringId.ObtainDragonStage25Answer2 -> R.string.ObtainDragonStage25Answer2
        StringId.ObtainDragonStage25Answer3 -> R.string.ObtainDragonStage25Answer3
        StringId.ObtainDragonStage25Answer4 -> R.string.ObtainDragonStage25Answer4
        StringId.ObtainDragonStage25Answer5 -> R.string.ObtainDragonStage25Answer5
        StringId.ObtainDragonStage25Dialog1 -> R.string.ObtainDragonStage25Dialog1
        StringId.ObtainDragonStage25Answer6 -> R.string.ObtainDragonStage25Answer6
        StringId.ObtainDragonStage25Answer7 -> R.string.ObtainDragonStage25Answer7
        StringId.ObtainDragonStage25Dialog2 -> R.string.ObtainDragonStage25Dialog2
        StringId.ObtainDragonStage25Answer8 -> R.string.ObtainDragonStage25Answer8
        StringId.ObtainDragonStage25Answer9 -> R.string.ObtainDragonStage25Answer9
        StringId.ObtainDragonStage25Dialog3 -> R.string.ObtainDragonStage25Dialog3
        StringId.ObtainDragonStage25Dialog4 -> R.string.ObtainDragonStage25Dialog4
        StringId.ObtainDragonStage25Dialog6 -> R.string.ObtainDragonStage25Dialog6
        StringId.ObtainDragonStage25Dialog8 -> R.string.ObtainDragonStage25Dialog8
        StringId.ObtainDragonStage25Dialog10 -> R.string.ObtainDragonStage25Dialog10
        StringId.ObtainDragonStage25Dialog13 -> R.string.ObtainDragonStage25Dialog13
        StringId.ObtainDragonStage25Dialog14 -> R.string.ObtainDragonStage25Dialog14
        StringId.ObtainDragonStage25Dialog15 -> R.string.ObtainDragonStage25Dialog15
        StringId.ObtainDragonStage25Dialog16 -> R.string.ObtainDragonStage25Dialog16
        StringId.ObtainDragonStage25Dialog18 -> R.string.ObtainDragonStage25Dialog18
        StringId.QuestIsFinished -> R.string.QuestIsFinished
        StringId.QuestDescFrog -> R.string.QuestDescFrog
        StringId.QuestDescBober -> R.string.QuestDescBober
        StringId.QuestNameNecronomicon -> R.string.QuestNameNecronomicon
        StringId.QuestNameObtainFrogus -> R.string.QuestNameObtainFrogus
        StringId.QuestNameObtainBober -> R.string.QuestNameObtainBober
        StringId.QuestNameObtainFractal -> R.string.QuestNameObtainFractal
        StringId.QuestNameMeditation -> R.string.QuestNameMeditation
        StringId.QuestNameObtainDragon -> R.string.QuestNameObtainDragon
        StringId.QuestDescObtainFrogusStage0 -> R.string.QuestDescObtainFrogusStage0
        StringId.QuestDescObtainFrogusStage1 -> R.string.QuestDescObtainFrogusStage1
        StringId.QuestDescObtainFrogusStage2 -> R.string.QuestDescObtainFrogusStage2
        StringId.QuestDescObtainFrogusStage3 -> R.string.QuestDescObtainFrogusStage3
        StringId.QuestDescObtainFrogusStage4 -> R.string.QuestDescObtainFrogusStage4
        StringId.QuestDescObtainFrogusStage5 -> R.string.QuestDescObtainFrogusStage5
        StringId.QuestDescObtainFrogusStage6 -> R.string.QuestDescObtainFrogusStage6
        StringId.QuestDescNecronomiconStage0 -> R.string.QuestDescNecronomiconStage0
        StringId.QuestDescNecronomiconStage1 -> R.string.QuestDescNecronomiconStage1
        StringId.QuestDescNecronomiconStage2 -> R.string.QuestDescNecronomiconStage2
        StringId.QuestDescNecronomiconStage3 -> R.string.QuestDescNecronomiconStage3
        StringId.QuestDescNecronomiconStage4 -> R.string.QuestDescNecronomiconStage4
        StringId.QuestDescNecronomiconStage5 -> R.string.QuestDescNecronomiconStage5
        StringId.QuestDescNecronomiconStage6 -> R.string.QuestDescNecronomiconStage6
        StringId.QuestDescNecronomiconStage7 -> R.string.QuestDescNecronomiconStage7
        StringId.QuestDescNecronomiconStage8 -> R.string.QuestDescNecronomiconStage8
        StringId.QuestDescNecronomiconStage9Use -> R.string.QuestDescNecronomiconStage9Use
        StringId.QuestDescNecronomiconStage9Destroy -> R.string.QuestDescNecronomiconStage9Destroy
        is StringId.QuestDescObtainBoberStage0 -> error("QuestDescObtainBoberStage0 requires formatting and should not be mapped with toResId()")
        StringId.QuestDescObtainBoberStage1 -> R.string.QuestDescObtainBoberStage1
        StringId.QuestDescObtainBoberStage2 -> R.string.QuestDescObtainBoberStage2
        StringId.QuestDescObtainBoberStage3 -> R.string.QuestDescObtainBoberStage3
        StringId.QuestDescObtainBoberStage4 -> R.string.QuestDescObtainBoberStage4
        StringId.QuestDescObtainBoberStage5 -> R.string.QuestDescObtainBoberStage5
        StringId.QuestDescObtainBoberStage6 -> R.string.QuestDescObtainBoberStage6
        StringId.QuestDescObtainBoberStage7 -> R.string.QuestDescObtainBoberStage7
        StringId.QuestDescObtainBoberStage8 -> R.string.QuestDescObtainBoberStage8
        StringId.QuestDescObtainBoberStage9 -> R.string.QuestDescObtainBoberStage9
        StringId.QuestDescObtainBoberStage10 -> R.string.QuestDescObtainBoberStage10
        StringId.QuestDescObtainBoberStage11 -> R.string.QuestDescObtainBoberStage11
        StringId.QuestDescObtainBoberStage12 -> R.string.QuestDescObtainBoberStage12
        is StringId.QuestDescObtainFractalStage0 -> error("QuestDescObtainFractalStage0 requires formatting and should not be mapped with toResId()")
        StringId.QuestDescObtainFractalStage1 -> R.string.QuestDescObtainFractalStage1
        StringId.QuestDescObtainFractalStage2 -> R.string.QuestDescObtainFractalStage2
        StringId.QuestDescObtainFractalStage3 -> R.string.QuestDescObtainFractalStage3
        StringId.QuestDescObtainFractalStage4 -> R.string.QuestDescObtainFractalStage4
        StringId.QuestDescObtainFractalStage5 -> R.string.QuestDescObtainFractalStage5
        StringId.QuestDescObtainFractalStage6 -> R.string.QuestDescObtainFractalStage6
        StringId.QuestDescObtainFractalStage7 -> R.string.QuestDescObtainFractalStage7
        StringId.QuestDescObtainFractalStage8 -> R.string.QuestDescObtainFractalStage8
        is StringId.QuestDescMeditationStage0 -> error("QuestDescMeditationStage0 requires formatting and should not be mapped with toResId()")
        StringId.QuestDescMeditationStage1 -> R.string.QuestDescMeditationStage1
        StringId.QuestDescMeditationStage2 -> R.string.QuestDescMeditationStage2
        StringId.QuestDescMeditationStage3 -> R.string.QuestDescMeditationStage3
        StringId.QuestDescMeditationStage4 -> R.string.QuestDescMeditationStage4
        is StringId.QuestDescObtainDragonStage0 -> error("QuestDescObtainDragonStage0 requires formatting and should not be mapped with toResId()")
        StringId.QuestDescObtainDragonStage1 -> R.string.QuestDescObtainDragonStage1
        StringId.QuestDescObtainDragonStage2 -> R.string.QuestDescObtainDragonStage2
        StringId.QuestDescObtainDragonStage3 -> R.string.QuestDescObtainDragonStage3
        StringId.QuestDescObtainDragonStage4 -> R.string.QuestDescObtainDragonStage4
        StringId.QuestDescObtainDragonStage5 -> R.string.QuestDescObtainDragonStage5
        StringId.QuestDescObtainDragonStage6 -> R.string.QuestDescObtainDragonStage6
        StringId.QuestDescObtainDragonStage7 -> R.string.QuestDescObtainDragonStage7
        StringId.QuestDescObtainDragonStage8 -> R.string.QuestDescObtainDragonStage8
        StringId.QuestDescObtainDragonStage9 -> R.string.QuestDescObtainDragonStage9
        StringId.QuestDescObtainDragonStage10 -> R.string.QuestDescObtainDragonStage10
        StringId.QuestDescObtainDragonStage11 -> R.string.QuestDescObtainDragonStage11
        StringId.QuestDescObtainDragonStage12 -> R.string.QuestDescObtainDragonStage12
        StringId.QuestDescObtainDragonStage13 -> R.string.QuestDescObtainDragonStage13
        StringId.QuestDescObtainDragonStage14 -> R.string.QuestDescObtainDragonStage14
        StringId.QuestDescObtainDragonStage15 -> R.string.QuestDescObtainDragonStage15
        StringId.QuestDescObtainDragonStage16 -> R.string.QuestDescObtainDragonStage16
        StringId.QuestDescObtainDragonStage17 -> R.string.QuestDescObtainDragonStage17
        StringId.QuestDescObtainDragonStage18 -> R.string.QuestDescObtainDragonStage18
        StringId.QuestDescObtainDragonStage19 -> R.string.QuestDescObtainDragonStage19
        StringId.QuestDescObtainDragonStage20 -> R.string.QuestDescObtainDragonStage20
        StringId.QuestDescObtainDragonStage21 -> R.string.QuestDescObtainDragonStage21
        StringId.QuestDescObtainDragonStage22 -> R.string.QuestDescObtainDragonStage22
        StringId.QuestDescObtainDragonStage23 -> R.string.QuestDescObtainDragonStage23
        StringId.QuestDescObtainDragonStage24 -> R.string.QuestDescObtainDragonStage24
        StringId.QuestDescObtainDragonStage25YesNecro -> R.string.QuestDescObtainDragonStage25YesNecro
        StringId.QuestDescObtainDragonStage25NoNecro -> R.string.QuestDescObtainDragonStage25NoNecro
        StringId.QuestDescObtainDragonStage26 -> R.string.QuestDescObtainDragonStage26
        StringId.QuestDescObtainDragonStage27 -> R.string.QuestDescObtainDragonStage27
        StringId.ItemDescNecronomicon -> R.string.ItemDescNecronomicon
        StringId.ItemDescPieceOfCloth -> R.string.ItemDescPieceOfCloth
        StringId.ItemDescMysteriousBook -> R.string.ItemDescMysteriousBook
        StringId.ItemDescFish -> R.string.ItemDescFish
        StringId.ItemDescFrogusEgg -> R.string.ItemDescFrogusEgg
        StringId.ItemDescDogusEgg -> R.string.ItemDescDogusEgg
        StringId.ItemDescCatusEgg -> R.string.ItemDescCatusEgg
        StringId.ItemDescBoberEgg -> R.string.ItemDescBoberEgg
        StringId.ItemDescDragonEgg -> R.string.ItemDescDragonEgg
        StringId.ItemDescBasket -> R.string.ItemDescBasket
        StringId.ItemDescTwoMeterRuler -> R.string.ItemDescTwoMeterRuler
        StringId.ItemDescTenCentimeterRuler -> R.string.ItemDescTenCentimeterRuler
        StringId.ItemDescMathBook -> R.string.ItemDescMathBook
        StringId.ItemDescMemoryOfMage -> R.string.ItemDescMemoryOfMage
        StringId.ItemDescMemoryOfWarrior -> R.string.ItemDescMemoryOfWarrior
        StringId.ItemDescMemoryOfBard -> R.string.ItemDescMemoryOfBard
        StringId.ItemDescMemoryOfSmith -> R.string.ItemDescMemoryOfSmith
        StringId.ItemDescCurseOfMage -> R.string.ItemDescCurseOfMage
        StringId.ItemDescCurseOfWarrior -> R.string.ItemDescCurseOfWarrior
        StringId.ItemDescCurseOfBard -> R.string.ItemDescCurseOfBard
        StringId.ItemDescCurseOfSmith -> R.string.ItemDescCurseOfSmith
    }
}