package bav.petus.android.ui.common

import bav.petus.android.R
import bav.petus.core.resources.StringId

fun StringId.toResId(): Int {
    return when (this) {
        StringId.ZooScreenTitle -> R.string.ZooScreenTitle
        StringId.CemeteryScreenTitle -> R.string.CemeteryScreenTitle
        StringId.ProfileScreenTitle -> R.string.ProfileScreenTitle
        StringId.WeatherScreenTitle -> R.string.WeatherScreenTitle
        StringId.QuestsScreenTitle -> R.string.QuestsScreenTitle
        StringId.PetTypeDescriptionCatus -> R.string.PetTypeDescriptionCatus
        StringId.PetTypeDescriptionDogus -> R.string.PetTypeDescriptionDogus
        StringId.PetTypeDescriptionFrogus -> R.string.PetTypeDescriptionFrogus
        StringId.PetTypeDescriptionBober -> R.string.PetTypeDescriptionBober
        StringId.PetTypeDescriptionFractal -> R.string.PetTypeDescriptionFractal
        StringId.WhatIsGoingOnWithYou -> R.string.WhatIsGoingOnWithYou
        StringId.WhatIsGoingOnWithYouLatin -> R.string.WhatIsGoingOnWithYouLatin
        StringId.WhatIsGoingOnWithYouPolish -> R.string.WhatIsGoingOnWithYouPolish
        StringId.BeingBetter -> R.string.BeenBetter
        StringId.IShouldGo -> R.string.IShouldGo
        StringId.SeeYa -> R.string.SeeYa
        StringId.ByeBye -> R.string.ByeBye
        StringId.Sure -> R.string.Sure
        StringId.Ok -> R.string.Ok
        StringId.Thanks -> R.string.Thanks
        StringId.Use -> R.string.Use
        StringId.Destroy -> R.string.Destroy
        StringId.IAmOkayHowAreYou -> R.string.IAmOkayHowAreYou
        StringId.IAmSick -> R.string.IAmSick
        StringId.IAmSickLatin -> R.string.IAmSickLatin
        StringId.IAmSickPolish -> R.string.IAmSickPolish
        StringId.IAmHungry -> R.string.IAmHungry
        StringId.IAmHungryLatin -> R.string.IAmHungryLatin
        StringId.IAmHungryPolish -> R.string.IAmHungryPolish
        StringId.IPooped -> R.string.IPooped
        StringId.IPoopedLatin -> R.string.IPoopedLatin
        StringId.IPoopedPolish -> R.string.IPoopedPolish
        StringId.IAmBored -> R.string.IAmBored
        StringId.IAmBoredLatin -> R.string.IAmBoredLatin
        StringId.IAmBoredPolish -> R.string.IAmBoredPolish
        StringId.IAmStillAngryAfterForceWakeUp -> R.string.IAmStillAngryAfterForceWakeUp
        StringId.IAmStillAngryAfterForceWakeUpLatin -> R.string.IAmStillAngryAfterForceWakeUpLatin
        StringId.IAmStillAngryAfterForceWakeUpPolish -> R.string.IAmStillAngryAfterForceWakeUpPolish
        StringId.IAmHalfHp -> R.string.IAmHalfHp
        StringId.IAmHalfHpLatin -> R.string.IAmHalfHpLatin
        StringId.IAmHalfHpPolish -> R.string.IAmHalfHpPolish
        StringId.IAmGood -> R.string.IAmGood
        StringId.IAmGoodLatin -> R.string.IAmGoodLatin
        StringId.IAmGoodPolish -> R.string.IAmGoodPolish
        is StringId.IWillDie -> error("IWillDie requires formatting and should not be mapped with toResId()")
        is StringId.IWillDieLatin -> error("IWillDieLatin requires formatting and should not be mapped with toResId()")
        is StringId.IWillDiePolish -> error("IWillDiePolish requires formatting and should not be mapped with toResId()")
        StringId.NecronomiconStage3AnswerOption0 -> R.string.NecronomiconStage3AnswerOption0
        StringId.NecronomiconStage3CommonDialog -> R.string.NecronomiconStage3CommonDialog
        StringId.NecronomiconStage3DogDialog -> R.string.NecronomiconStage3DogDialog
        StringId.NecronomiconStage3DogDialogAnswerOption0 -> R.string.NecronomiconStage3DogDialogAnswerOption0
        StringId.NecronomiconStage5AnswerOption0 -> R.string.NecronomiconStage5AnswerOption0
        StringId.NecronomiconStage5DogDialog -> R.string.NecronomiconStage5DogDialog
        StringId.NecronomiconStage6AnswerOption0 -> R.string.NecronomiconStage6AnswerOption0
        StringId.NecronomiconStage6DogDialog -> R.string.NecronomiconStage6DogDialog
        StringId.NecronomiconStage7DogDialog0 -> R.string.NecronomiconStage7DogDialog0
        StringId.NecronomiconStage7AnswerOption0 -> R.string.NecronomiconStage7AnswerOption0
        StringId.NecronomiconStage7DogDialog1 -> R.string.NecronomiconStage7DogDialog1
        StringId.NecronomiconStage7DogDialog2 -> R.string.NecronomiconStage7DogDialog2
        StringId.NecronomiconStage8AnswerOption0 -> R.string.NecronomiconStage8AnswerOption0
        StringId.NecronomiconStage8Dialog0 -> R.string.NecronomiconStage8Dialog0
        StringId.NecronomiconStage8Dialog1 -> R.string.NecronomiconStage8Dialog1
        StringId.MysteriousBook -> R.string.MysteriousBook
        StringId.Necronomicon -> R.string.Necronomicon
        StringId.PieceOfCloth -> R.string.PieceOfCloth
        StringId.Fish -> R.string.Fish
        StringId.FrogusEgg -> R.string.FrogusEgg
        StringId.DogusEgg -> R.string.DogusEgg
        StringId.CatusEgg -> R.string.CatusEgg
        StringId.BoberEgg -> R.string.BoberEgg
        StringId.Basket -> R.string.Basket
        StringId.TwoMeterRuler -> R.string.TwoMeterRuler
        StringId.TenCentimeterRuler -> R.string.TenCentimeterRuler
        StringId.MathBook -> R.string.MathBook
        StringId.HistoryEventPetBecomeAdult -> R.string.HistoryEventPetBecomeAdult
        StringId.HistoryEventPetBecomeNewborn -> R.string.HistoryEventPetBecomeNewborn
        StringId.HistoryEventPetBecomeOld -> R.string.HistoryEventPetBecomeOld
        StringId.HistoryEventPetBecomeTeen -> R.string.HistoryEventPetBecomeTeen
        StringId.HistoryEventPetBuried -> R.string.HistoryEventPetBuried
        StringId.HistoryEventPetForgotten -> R.string.HistoryEventPetForgotten
        StringId.HistoryEventPetCleanUp -> R.string.HistoryEventPetCleanUp
        StringId.HistoryEventPetCreated -> R.string.HistoryEventPetCreated
        StringId.HistoryEventPetDied -> R.string.HistoryEventPetDied
        StringId.HistoryEventPetFeed -> R.string.HistoryEventPetFeed
        StringId.HistoryEventPetForciblyWakeUp -> R.string.HistoryEventPetForciblyWakeUp
        StringId.HistoryEventPetGetHealed -> R.string.HistoryEventPetGetHealed
        StringId.HistoryEventPetGetIll -> R.string.HistoryEventPetGetIll
        StringId.HistoryEventPetPlay -> R.string.HistoryEventPetPlay
        StringId.HistoryEventPetPoop -> R.string.HistoryEventPetPoop
        StringId.HistoryEventPetResurrected -> R.string.HistoryEventPetResurrected
        StringId.HistoryEventPetSleep -> R.string.HistoryEventPetSleep
        StringId.HistoryEventPetWakeUp -> R.string.HistoryEventPetWakeUp
        StringId.Necromancy -> R.string.Necromancy
        StringId.Meditation -> R.string.Meditation
        StringId.ObtainFrogusStage1Answer0 -> R.string.ObtainFrogusStage1Answer0
        StringId.ObtainFrogusStage1Dialog0 -> R.string.ObtainFrogusStage1Dialog0
        StringId.ObtainFrogusStage1Answer1 -> R.string.ObtainFrogusStage1Answer1
        StringId.ObtainFrogusStage3Answer0 -> R.string.ObtainFrogusStage3Answer0
        StringId.ObtainFrogusStage3Dialog0 -> R.string.ObtainFrogusStage3Dialog0
        StringId.ObtainFrogusStage3Answer1 -> R.string.ObtainFrogusStage3Answer1
        StringId.ObtainFrogusStage5Answer0 -> R.string.ObtainFrogusStage5Answer0
        StringId.ObtainFrogusStage5Dialog0 -> R.string.ObtainFrogusStage5Dialog0
        StringId.ObtainFrogusStage5Answer1 -> R.string.ObtainFrogusStage5Answer1
        StringId.ObtainBoberStage2Answer0 -> R.string.ObtainBoberStage2Answer0
        StringId.ObtainBoberStage2Answer1 -> R.string.ObtainBoberStage2Answer1
        StringId.ObtainBoberStage2Dialog0 -> R.string.ObtainBoberStage2Dialog0
        StringId.ObtainBoberStage2Dialog1 -> R.string.ObtainBoberStage2Dialog1
        StringId.ObtainBoberStage3Answer0 -> R.string.ObtainBoberStage3Answer0
        StringId.ObtainBoberStage3Dialog0 -> R.string.ObtainBoberStage3Dialog0
        StringId.ObtainBoberStage4Dialog0 -> R.string.ObtainBoberStage4Dialog0
        StringId.ObtainBoberStage6Answer0 -> R.string.ObtainBoberStage6Answer0
        StringId.ObtainBoberStage6Dialog0 -> R.string.ObtainBoberStage6Dialog0
        StringId.ObtainBoberStage6Dialog1 -> R.string.ObtainBoberStage6Dialog1
        StringId.ObtainBoberStage8Answer0 -> R.string.ObtainBoberStage8Answer0
        StringId.ObtainBoberStage8Dialog0 -> R.string.ObtainBoberStage8Dialog0
        StringId.ObtainBoberStage9Answer0 -> R.string.ObtainBoberStage9Answer0
        StringId.ObtainBoberStage9Dialog0 -> R.string.ObtainBoberStage9Dialog0
        StringId.ObtainBoberStage9Dialog1 -> R.string.ObtainBoberStage9Dialog1
        StringId.ObtainBoberStage9Dialog2 -> R.string.ObtainBoberStage9Dialog2
        StringId.ObtainBoberStage10Answer0 -> R.string.ObtainBoberStage10Answer0
        StringId.ObtainBoberStage10Dialog0 -> R.string.ObtainBoberStage10Dialog0
        StringId.ObtainBoberStage11Dialog0 -> R.string.ObtainBoberStage11Dialog0
        StringId.ObtainBoberStage11Answer0 -> R.string.ObtainBoberStage11Answer0
        StringId.ObtainFractalStage1Answer0 -> R.string.ObtainFractalStage1Answer0
        StringId.ObtainFractalStage1Dialog0 -> R.string.ObtainFractalStage1Dialog0
        StringId.ObtainFractalStage1Dialog1 -> R.string.ObtainFractalStage1Dialog1
        StringId.ObtainFractalStage1Answer1 -> R.string.ObtainFractalStage1Answer1
        StringId.ObtainFractalStage3Answer0 -> R.string.ObtainFractalStage3Answer0
        StringId.ObtainFractalStage3Dialog0 -> R.string.ObtainFractalStage3Dialog0
        StringId.ObtainFractalStage3Answer1 -> R.string.ObtainFractalStage3Answer1
        StringId.ObtainFractalStage5Answer0 -> R.string.ObtainFractalStage5Answer0
        StringId.ObtainFractalStage5Dialog0 -> R.string.ObtainFractalStage5Dialog0
        StringId.ObtainFractalStage5Answer1 -> R.string.ObtainFractalStage5Answer1
        StringId.ObtainFractalStage6Answer0 -> R.string.ObtainFractalStage6Answer0
        StringId.ObtainFractalStage6Dialog0 -> R.string.ObtainFractalStage6Dialog0
        StringId.ObtainFractalStage6Answer1 -> R.string.ObtainFractalStage6Answer1
        StringId.QuestIsFinished -> R.string.QuestIsFinished
        StringId.QuestNameNecronomicon -> R.string.QuestNameNecronomicon
        StringId.QuestNameObtainFrogus -> R.string.QuestNameObtainFrogus
        StringId.QuestNameObtainBober -> R.string.QuestNameObtainBober
        StringId.QuestNameObtainFractal -> R.string.QuestNameObtainFractal
        StringId.QuestDescObtainFrogusStage0 -> R.string.QuestDescObtainFrogusStage0
        StringId.QuestDescObtainFrogusStage1 -> R.string.QuestDescObtainFrogusStage1
        StringId.QuestDescObtainFrogusStage2 -> R.string.QuestDescObtainFrogusStage2
        StringId.QuestDescObtainFrogusStage3 -> R.string.QuestDescObtainFrogusStage3
        StringId.QuestDescObtainFrogusStage4 -> R.string.QuestDescObtainFrogusStage4
        StringId.QuestDescObtainFrogusStage5 -> R.string.QuestDescObtainFrogusStage5
        StringId.QuestDescObtainFrogusStage6 -> R.string.QuestDescObtainFrogusStage6
        StringId.QuestDescNecronomiconStage0 -> R.string.QuestDescNecronomiconStage0
        StringId.QuestDescNecronomiconStage1 -> R.string.QuestDescNecronomiconStage1
        StringId.QuestDescNecronomiconStage2 -> R.string.QuestDescNecronomiconStage2
        StringId.QuestDescNecronomiconStage3 -> R.string.QuestDescNecronomiconStage3
        StringId.QuestDescNecronomiconStage4 -> R.string.QuestDescNecronomiconStage4
        StringId.QuestDescNecronomiconStage5 -> R.string.QuestDescNecronomiconStage5
        StringId.QuestDescNecronomiconStage6 -> R.string.QuestDescNecronomiconStage6
        StringId.QuestDescNecronomiconStage7 -> R.string.QuestDescNecronomiconStage7
        StringId.QuestDescNecronomiconStage8 -> R.string.QuestDescNecronomiconStage8
        StringId.QuestDescNecronomiconStage9Use -> R.string.QuestDescNecronomiconStage9Use
        StringId.QuestDescNecronomiconStage9Destroy -> R.string.QuestDescNecronomiconStage9Destroy
        StringId.QuestDescObtainBoberStage0 -> R.string.QuestDescObtainBoberStage0
        StringId.QuestDescObtainBoberStage1 -> R.string.QuestDescObtainBoberStage1
        StringId.QuestDescObtainBoberStage2 -> R.string.QuestDescObtainBoberStage2
        StringId.QuestDescObtainBoberStage3 -> R.string.QuestDescObtainBoberStage3
        StringId.QuestDescObtainBoberStage4 -> R.string.QuestDescObtainBoberStage4
        StringId.QuestDescObtainBoberStage5 -> R.string.QuestDescObtainBoberStage5
        StringId.QuestDescObtainBoberStage6 -> R.string.QuestDescObtainBoberStage6
        StringId.QuestDescObtainBoberStage7 -> R.string.QuestDescObtainBoberStage7
        StringId.QuestDescObtainBoberStage8 -> R.string.QuestDescObtainBoberStage8
        StringId.QuestDescObtainBoberStage9 -> R.string.QuestDescObtainBoberStage9
        StringId.QuestDescObtainBoberStage10 -> R.string.QuestDescObtainBoberStage10
        StringId.QuestDescObtainBoberStage11 -> R.string.QuestDescObtainBoberStage11
        StringId.QuestDescObtainBoberStage12 -> R.string.QuestDescObtainBoberStage12
        StringId.QuestDescObtainFractalStage0 -> R.string.QuestDescObtainFractalStage0
        StringId.QuestDescObtainFractalStage1 -> R.string.QuestDescObtainFractalStage1
        StringId.QuestDescObtainFractalStage2 -> R.string.QuestDescObtainFractalStage2
        StringId.QuestDescObtainFractalStage3 -> R.string.QuestDescObtainFractalStage3
        StringId.QuestDescObtainFractalStage4 -> R.string.QuestDescObtainFractalStage4
        StringId.QuestDescObtainFractalStage5 -> R.string.QuestDescObtainFractalStage5
        StringId.QuestDescObtainFractalStage6 -> R.string.QuestDescObtainFractalStage6
        StringId.QuestDescObtainFractalStage7 -> R.string.QuestDescObtainFractalStage7
        StringId.QuestDescObtainFractalStage8 -> R.string.QuestDescObtainFractalStage8
    }
}