import SwiftUI
import shared

extension StringId {
    var localized: String {
        let resId: String.LocalizationValue = switch onEnum(of: self) {
        case .petTypeDescriptionCatus: "PetTypeDescriptionCatus"
        case .petTypeDescriptionDogus: "PetTypeDescriptionDogus"
        case .petTypeDescriptionFrogus: "PetTypeDescriptionFrogus"
        case .mysteriousBook: "MysteriousBook"
        case .necronomicon: "Necronomicon"
        case .pieceOfCloth: "PieceOfCloth"
        case .fish: "Fish"
        case .frogusEgg: "FrogusEgg"
        case .whatIsGoingOnWithYou: "WhatIsGoingOnWithYou"
        case .whatIsGoingOnWithYouLatin: "WhatIsGoingOnWithYouLatin"
        case .beingBetter: "BeenBetter"
        case .byeBye: "ByeBye"
        case .iShouldGo: "IShouldGo"
        case .seeYa: "SeeYa"
        case .sure: "Sure"
        case .ok: "Ok"
        case .thanks: "Thanks"
        case .use: "Use"
        case .destroy: "Destroy"
        case .iAmOkayHowAreYou: "IAmOkayHowAreYou"
        case .iAmSick: "IAmSick"
        case .iAmSickLatin: "IAmSickLatin"
        case .iAmHungry: "IAmHungry"
        case .iAmHungryLatin: "IAmHungryLatin"
        case .iPooped: "IPooped"
        case .iPoopedLatin: "IPoopedLatin"
        case .iAmBored: "IAmBored"
        case .iAmBoredLatin: "IAmBoredLatin"
        case .iAmStillAngryAfterForceWakeUp: "IAmStillAngryAfterForceWakeUp"
        case .iAmStillAngryAfterForceWakeUpLatin: "IAmStillAngryAfterForceWakeUpLatin"
        case .iAmHalfHp: "IAmHalfHp"
        case .iAmHalfHpLatin: "IAmHalfHpLatin"
        case .iAmGood: "IAmGood"
        case .iAmGoodLatin: "IAmGoodLatin"
        case .necronomiconStage3AnswerOption0: "NecronomiconStage3AnswerOption0"
        case .necronomiconStage3CommonDialog: "NecronomiconStage3CommonDialog"
        case .necronomiconStage3DogDialog: "NecronomiconStage3DogDialog"
        case .necronomiconStage3DogDialogAnswerOption0: "NecronomiconStage3DogDialogAnswerOption0"
        case .necronomiconStage5AnswerOption0: "NecronomiconStage5AnswerOption0"
        case .necronomiconStage5DogDialog: "NecronomiconStage5DogDialog"
        case .necronomiconStage6AnswerOption0: "NecronomiconStage6AnswerOption0"
        case .necronomiconStage6DogDialog: "NecronomiconStage6DogDialog"
        case .necronomiconStage7DogDialog0: "NecronomiconStage7DogDialog0"
        case .necronomiconStage7AnswerOption0: "NecronomiconStage7AnswerOption0"
        case .necronomiconStage7DogDialog1: "NecronomiconStage7DogDialog1"
        case .necronomiconStage7DogDialog2: "NecronomiconStage7DogDialog2"
        case .necronomiconStage8AnswerOption0: "NecronomiconStage8AnswerOption0"
        case .necronomiconStage8Dialog0: "NecronomiconStage8Dialog0"
        case .necronomiconStage8Dialog1: "NecronomiconStage8Dialog1"
        case .cemeteryScreenTitle: "CemeteryScreenTitle"
        case .profileScreenTitle: "ProfileScreenTitle"
        case .weatherScreenTitle: "WeatherScreenTitle"
        case .zooScreenTitle: "ZooScreenTitle"
        case .historyEventPetBecomeAdult: "HistoryEventPetBecomeAdult"
        case .historyEventPetBecomeNewborn: "HistoryEventPetBecomeNewborn"
        case .historyEventPetBecomeOld: "HistoryEventPetBecomeOld"
        case .historyEventPetBecomeTeen: "HistoryEventPetBecomeTeen"
        case .historyEventPetBuried: "HistoryEventPetBuried"
        case .historyEventPetCleanUp: "HistoryEventPetCleanUp"
        case .historyEventPetCreated: "HistoryEventPetCreated"
        case .historyEventPetDied: "HistoryEventPetDied"
        case .historyEventPetFeed: "HistoryEventPetFeed"
        case .historyEventPetForciblyWakeUp: "HistoryEventPetForciblyWakeUp"
        case .historyEventPetGetHealed: "HistoryEventPetGetHealed"
        case .historyEventPetGetIll: "HistoryEventPetGetIll"
        case .historyEventPetPlay: "HistoryEventPetPlay"
        case .historyEventPetPoop: "HistoryEventPetPoop"
        case .historyEventPetResurrected: "HistoryEventPetResurrected"
        case .historyEventPetSleep: "HistoryEventPetSleep"
        case .historyEventPetWakeUp: "HistoryEventPetWakeUp"
        case .necromancy: "Necromancy"
        case .obtainFrogusStage1Answer0: "ObtainFrogusStage1Answer0"
        case .obtainFrogusStage1Dialog0: "ObtainFrogusStage1Dialog0"
        case .obtainFrogusStage1Answer1: "ObtainFrogusStage1Answer1"
        case .obtainFrogusStage3Answer0: "ObtainFrogusStage3Answer0"
        case .obtainFrogusStage3Dialog0: "ObtainFrogusStage3Dialog0"
        case .obtainFrogusStage3Answer1: "ObtainFrogusStage3Answer1"
        case .obtainFrogusStage5Answer0: "ObtainFrogusStage5Answer0"
        case .obtainFrogusStage5Dialog0: "ObtainFrogusStage5Dialog0"
        case .obtainFrogusStage5Answer1: "ObtainFrogusStage5Answer1"
        }
        
        return String(localized: resId)
    }
}
