package bav.petus.core.resources

enum class ImageId {
    //region Buttons
    BuryCat,
    BuryDog,
    BuryFrog,
    CleanUpCat,
    CleanUpDog,
    CleanUpFrog,
    FeedCat,
    FeedDog,
    FeedFrog,
    HealCat,
    HealDog,
    HealFrog,
    PlayCat,
    PlayDog,
    PlayFrog,
    ResurrectCat,
    ResurrectDog,
    ResurrectFrog,
    SpeakCat,
    SpeakDog,
    SpeakFrog,
    WakeUpCat,
    WakeUpDog,
    WakeUpFrog,
    //endregion
    
    //region Catus
    CatAdultActive,
    CatAdultDead,
    CatAdultHungry,
    CatAdultIll,
    CatAdultPoop,
    CatAdultSleep,
    CatAdultZombie,
    CatEgg,
    CatGrave,
    CatNewbornActive,
    CatNewbornDead,
    CatNewbornHungry,
    CatNewbornIll,
    CatNewbornPoop,
    CatNewbornSleep,
    CatNewbornZombie,
    CatOldActive,
    CatOldDead,
    CatOldHungry,
    CatOldIll,
    CatOldPoop,
    CatOldSleep,
    CatOldZombie,
    //endregion

    //region Dogus
    DogAdultActive,
    DogAdultDead,
    DogAdultHungry,
    DogAdultIll,
    DogAdultPoop,
    DogAdultSleep,
    DogAdultZombie,
    DogEgg,
    DogGrave,
    DogNewbornActive,
    DogNewbornDead,
    DogNewbornHungry,
    DogNewbornIll,
    DogNewbornPoop,
    DogNewbornSleep,
    DogNewbornZombie,
    DogOldActive,
    DogOldDead,
    DogOldHungry,
    DogOldIll,
    DogOldPoop,
    DogOldSleep,
    DogOldZombie,
    //endregion

    //region Frogus
    FrogAdultActive,
    FrogAdultDead,
    FrogAdultHungry,
    FrogAdultIll,
    FrogAdultPoop,
    FrogAdultSleep,
    FrogAdultZombie,
    FrogEgg,
    FrogGrave,
    FrogNewbornActive,
    FrogNewbornDead,
    FrogNewbornHungry,
    FrogNewbornIll,
    FrogNewbornPoop,
    FrogNewbornSleep,
    FrogNewbornZombie,
    FrogOldActive,
    FrogOldDead,
    FrogOldHungry,
    FrogOldIll,
    FrogOldPoop,
    FrogOldSleep,
    FrogOldZombie,
    //endregion

    //region Bober
    BoberAdultActive,
    BoberAdultDead,
    BoberAdultHungry,
    BoberAdultIll,
    BoberAdultPoop,
    BoberAdultSleep,
    BoberAdultZombie,
    BoberEgg,
    BoberGrave,
    BoberNewbornActive,
    BoberNewbornDead,
    BoberNewbornHungry,
    BoberNewbornIll,
    BoberNewbornPoop,
    BoberNewbornSleep,
    BoberNewbornZombie,
    BoberOldActive,
    BoberOldDead,
    BoberOldHungry,
    BoberOldIll,
    BoberOldPoop,
    BoberOldSleep,
    BoberOldZombie,
    //endregion

    //region Common
    DugOutGrave,
    UserProfileAvatar,
    //endregion
    ;
}